### ISSUE TITLE
Not able to read music if the file path contains spaces on windows

### ISSUE THREAD

**Issue by alexis35115** [mobiletechtracker/NetCoreAudio#6]
it's not possible to read music from file that contains spaces in path

**Comment by fiodarsazanavets** [comment]
This issue has now been resolved. The fix is available in version 1.6.2.

Since "status" MCI command doesn't work with file paths with whitespaces, even if they are enclosed in quotes, and not every machine has the correct codec to be able to define the right device for MP3 playback, the issue has been resolved by copying the file into a temporary location and removing any whitespaces from the file name.
